# Generated by Django 5.0.3 on 2024-03-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_signin_delete_sign_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=152)),
                ('password', models.CharField(max_length=152)),
            ],
        ),
        migrations.DeleteModel(
            name='SignIn',
        ),
    ]
