# Generated by Django 5.0.3 on 2024-03-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_sign_in_delete_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('re_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='sign_in',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
